### ISSUE TITLE
Client IP in den UI Skizzen 

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#119]
Warum ist eigentlich die Client IP in den UI Skizzen umstellbar?

**Comment by HansMartinA** [comment]
Ist sie nicht, sieht nur so aus. "Live" gesehen, kann man sie nicht ändern und es erscheint ein Tooltip "Kann nicht geändert werden". Kann ich aber noch ändern. Allerdings erst, wenn klar ist, wie wir es mit den Ports machen (dann sind es mehrere Änderungen auf einmal).

**Comment by ByteHamster** [comment]
Ah okay. Dann bin ich einverstanden ;)
