### ISSUE TITLE
Produktumgebung reduzieren

### ISSUE THREAD

**Issue by NikoWil** [ByteHamster/PSE#133]
Sollen wir die Produktumgebung noch reduzieren? Sprich, dass nur ein Betriebssystem nur unterstuezt werden  muss. Alles andere ist Bonus.

**Comment by ByteHamster** [comment]
Wir benutzen die Systeme alle zum Entwickeln. Denke das ist okay. Mint du und ich, Win10 Martin, Ubuntu Max

**Comment by ByteHamster** [comment]
Mint raus bitte
