### ISSUE TITLE
Dokument korrekturlesen

### ISSUE THREAD

**Issue by Dav1dK** [ByteHamster/PSE#171]
Die Benennung von Begriffen wie Mischtank/Mixtank oder Client/Clients sollte Dokumentenübergreifend und im Dokument konsistent sein. Die Ausnahme sind Namen von Klassen, die Englisch geschrieben werden.

**Comment by Dav1dK** [comment]
"typische Aktionen in OSIP" (Einleitung zu den Sequenzdiagrammen) umformulieren, um herauszustellen, dass das die komplexen Abläufe sind (das Kernstück der Anwendung)

**Comment by Dav1dK** [comment]
Kontrollieren, dass wir überall von "mehreren Wrappern" statt von "einem Wrapper" sprechen. (Bezieht sich auf die OPC UA Wrapper)

**Comment by NikoWil** [comment]
An einigen Stellen haben wir in den Kommentaren im Klassendiagramm Kurzformen wie "it's" statt "it is" verwendet.

In einem formalen/ technischen Dokument sollten wir nicht die umgangssprachliche Variante nehmen. Ich hab schon einige umgewandelt, bin aber nicht sicher ob ich alle gefunden habe.

**Comment by ByteHamster** [comment]
Oft genug steht auch `it's` da, obwohl es `its` heißen sollte...

**Comment by ByteHamster** [comment]
> An einigen Stellen haben wir in den Kommentaren im Klassendiagramm Kurzformen wie "it's" statt "it is" verwendet.

Done. Sind definitiv keine mehr drin (grep aufs Diagramm)

**Comment by ByteHamster** [comment]
> Kontrollieren, dass wir überall von "mehreren Wrappern" statt von "einem Wrapper" sprechen. (Bezieht sich auf die OPC UA Wrapper)

Wir haben nur einen Wrapper. Das sagt noch nichts über die Instanzen, die man dann von den Servern erstellt.

**Comment by Dav1dK** [comment]
>> Kontrollieren, dass wir überall von "mehreren Wrappern" statt von "einem Wrapper" sprechen. (Bezieht sich auf die OPC UA Wrapper)
>
> Wir haben nur einen Wrapper. Das sagt noch nichts über die Instanzen, die man dann von den Servern erstellt.

Wir haben den ServerWrapper und den ClientWrapper. Ich glaube darum geht es.
