### ISSUE TITLE
Verweis auf Anhang präzisieren

### ISSUE THREAD

**Issue by Dav1dK** [ByteHamster/PSE#172]
Der Verweis auf den Anhang mit den Klassenbeschreibungen sollte genauer sein (z.B. siehe Seite X)

**Comment by ByteHamster** [comment]
Seiten geht nicht. Wir binden das als eigenes PDF ein, nicht direkt in das andere Dokument (Sonst haben wir 8 Seiten Inhaltsverzeichnis)

**Comment by ByteHamster** [comment]
Sind sogar 12 Seiten ^^

**Comment by Dav1dK** [comment]
Ja wir sollten es trotzdem irgendwie besser erklären. Das war ein Kritikpunkt bei der Besprechung.

**Comment by marimbMax** [comment]
Wie machen wir es dann ?
