### ISSUE TITLE
Unforeseen problems

### ISSUE THREAD

**Issue by marimbMax** [ByteHamster/PSE#187]

**Comment by marimbMax** [comment]
Parser larger than expected.

**Comment by marimbMax** [comment]
SettingsWrapper classes are more work than expected.

**Comment by ByteHamster** [comment]
> There are no instantaneous subscriptions in OPC UA; notifications will always be published at the interval defined for the subscription

http://stackoverflow.com/a/42161092/4193263

Thus, we are using fast subscriptions for the alarms

**Comment by HansMartinA** [comment]
- Layout der Überwachungskonsole hat mehr Arbeit erfordert, bis es passend war.

- Benachrichtigung und Zustanshaltung der Ampel.

**Comment by marimbMax** [comment]
OSIP fills RAM memory somehow.

**Comment by ByteHamster** [comment]
Der Mensch von Milo löscht alte Versionen aus dem Repo und macht dadurch unsere Builds kaputt (schon 2x während der Implementierungsphase)
