### ISSUE TITLE
GUI Implementierung Niko

### ISSUE THREAD

**Issue by Dav1dK** [ByteHamster/PSE#191]
Simulation:
- [x] Drawer
- [x] Hauptfenster
- [x] Kontrolldialoge

Beginnt am 06.02.2017

**Comment by NikoWil** [comment]
Aenderungen:
Die Drawer erhalten noch Parameter rows und cols, um jeweils die Breite/ Hoehe der Abschnitte fuer jeden Tank auf dem Bildschirm berechnen zu koennen.
draw erhaelt den Parameter time, um die Weite der Drehung von Motor und Valve berechnen zu koennen.

**Comment by Dav1dK** [comment]
Schreibe das bitte in #186
