### ISSUE TITLE
Constants in model

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#206]
- Tank size
- Maximum motor speed
- Simulation step
- Temperature min/max for displaying
- Max throughput of valve
- Current throughput of valve

**Comment by ByteHamster** [comment]
Class with final public static constants

**Comment by Dav1dK** [comment]
Was ist "Max throughput of valve" und "Current throughput of valve". Und gelten die Temperaturen auch für das Model, oder nur für die View?

**Comment by ByteHamster** [comment]
Die Temperaturen braucht Martin. Damit er weiß, von wo bis wo die gauges darstellen sollen.

Bei valves kann es ja sein, dass der Tank drüber leer ist. Dann sind tatsächlicher Durchfluss und Ventilöffnung etwas anderes

**Comment by Dav1dK** [comment]
Und warum sollte das eine Konstante sein? Das ändert sich doch ständig.

**Comment by ByteHamster** [comment]
Das soll in die Pipes rein. Da passt der Titel nicht

**Comment by Dav1dK** [comment]
Es gibt bei der Pipe getThreshold() das den Ventilzustand in % zurückgibt und getMaxInput(), dass zurückgibt, wieviel man momenten (also beim aktuellen Ventilzustand) reinstecken kann. Aber was tatsächlich reingesteckt wird, weiß doch eigentlich der Controller wenn er Liquid vom Tank holt. Wofür dann diese Methode?

**Comment by ByteHamster** [comment]
Okay getMaxInput hatte ich übersehen

Current throughput: Damit die Gauge von Martin das anzeigen kann, das durch fließt. Sonst kann er nur die Öffnung anzeigen

**Comment by Dav1dK** [comment]
Aber an welcher Stelle der Pipe? Im Durchschnitt oder am Anfang oder am Ende?

**Comment by ByteHamster** [comment]
wow das wird sowieso nicht über opc ua übertragen. Dann muss Martin halt die Öffnung einfach in Prozent anzeigen.

**Comment by Dav1dK** [comment]
PR: #214
