### ISSUE TITLE
setInputTemperature

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#223]
setInputTemperature sollte range checks machen

**Comment by ByteHamster** [comment]
Warum ist die Funktion eigentlich im base model? Würde besser in die simulation passen. Dann müsste aber das scenario auch mit ProductionSiteSimulation laufen

**Comment by Dav1dK** [comment]
Warum nicht? Es ist ein Teil des Zustands der Produktionsanlage und es könnte ja auch sein, dass wir uns dazu entscheiden, es per OPC UA zu übertragen. Deswegen finde ich, dass die Input Temperatur im selben Package sein sollte, wie die Temperaturen der Tanks/Liquids.

**Comment by ByteHamster** [comment]
Okay. Dann nur noch das obere ;)
