### ISSUE TITLE
[monitoring-dashboard] Alarme und Konsole

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#268]
Deaktivierte Alarme sollten vielleicht in der Konsole eine eigene Farbe bekommen, zum Beispiel grau

**Comment by HansMartinA** [comment]
1. Die Konsole wird bisher nicht angesprochen.
2. Es fehlt ein Dialog, der bei ausgelösten Alarmen angezeigt wird.

**Comment by ByteHamster** [comment]
Meinte mit Konsole eigentlich die Überwachungskonsole als ganzes. Also diese Kreise sollten halt sichtbar deaktiviert werden, wenn man in den Einstellungen die Alarme deaktiviert

**Comment by HansMartinA** [comment]
Für die Alarme ist bereits grau vorgesehen, wenn sie deaktiviert sind. Dies wird allerdings erst sichtbar, nachdem die Einstellungen gespeichert wurden.
