### ISSUE TITLE
Lizenzen

### ISSUE THREAD

**Issue by HansMartinA** [ByteHamster/PSE#271]
Ins Über-Fenster müssen noch die Lizenzen für Milo (in beiden Programmen) und JFXtras (nur Überwachungskonsole) sowie die Version von OSIP.

**Comment by ByteHamster** [comment]
Mittlerweile macht es glaub sogar Sinn, dass wir die Lizenzen in eine Textdatei/HTML-Datei schreiben und dann von da aus im UI anzeigen. Das braucht nicht alles in den Translator.

**Comment by marimbMax** [comment]
Also ich wäre für Translator. So hat der Benutzer noch die Möglichkeit zu übersetzten, falls er es unbedingt will oder kann weiter die englische Version benutzen. Das schadet ja nicht.

**Comment by marimbMax** [comment]
Ok, das wird mit den drei Lizenzen echt viel. Vll doch Textdatei.
