### ISSUE TITLE
[Überwachungskonsole] Ampel

### ISSUE THREAD

**Issue by HansMartinA** [ByteHamster/PSE#28]
In der Überwachungskonsole ist eine allgemeine dreistufige Ampel eingeplant. Welche genaue Funktion hat sie und wann leuchtet welches Licht?

**Comment by Dav1dK** [comment]
Ich würde sagen, die Ampel hat einfach nur zwei Zustände, oder?
Grüne, wenn alles in Ordnung ist, und rot wenn es Alarme gab.

**Comment by HansMartinA** [comment]
Das klingt mir sinnvoll und, da sich bisher niemand weiteres dazu geäußert hat, werde ich das zum nächsten Pullrequest übernehmen.
