### ISSUE TITLE
Bundles vereinheitlichen

### ISSUE THREAD

**Issue by Dav1dK** [ByteHamster/PSE#280]
In der Simulation gibt es derzeit ein Bundle im Controller und in der View. Das sollte vermutlich alles in ein Bundle.

**Comment by Dav1dK** [comment]
Generell sind in der Simulation viele Strings unübersetzt oder werden nicht gefunden.

**Comment by ByteHamster** [comment]
Jap Simulation ist noch nicht übersetzt

**Comment by NikoWil** [comment]
Wurden jetzt alle in eine Datei verschoben
