### ISSUE TITLE
[Überwachungskonsole] Dauer Alarmanzeige

### ISSUE THREAD

**Issue by HansMartinA** [ByteHamster/PSE#29]
Wenn der Benutzer in der Überwachungskonsole über einen ausgelösten Alarm informiert wird, wie lange soll dieser angezeigt werden bzw. soll es dem Nutzer möglich sein, diesen auszuschalten oder zu ignorieren?

**Comment by HansMartinA** [comment]
Für die Dauer hätte ich festgelegt: Die Alarme werden so lange als ausgelöst angezeigt, bis die Fertigungssimulation meldet, die Alarme wurden behoben.

**Comment by ByteHamster** [comment]
Haben Alarme Anfang und Ende oder sind sie einzelne Events?

**Comment by ByteHamster** [comment]
Alarme sind also einzelne Events und haben keine Dauer. Würde also nur Dialogbox anzeigen, die Ampel richtet sich an die Werte der synchronen Aktualisierung von Werten

**Comment by HansMartinA** [comment]
Dialog ist hinzugefügt.

**Comment by ByteHamster** [comment]
Kann man den issue dann schließen?
