### ISSUE TITLE
Control window

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#294]
- Window soll beim Aufruf von `show` die Werte aus dem Model übernehmen, anstatt wieder die alten anzuzeigen. Ist gerade beim Reset wichtig.
- Es muss eine `disable()` Methode geben, die eine Änderung der ganzen UI Elemente blockiert (Überlauf)

**Comment by NikoWil** [comment]
Die Methode zum deaktivieren ist drin (noch kein PR, da das show/ hide auch noch mit dazu kann).

Show sollte ausserhalb des Resets kein Problem sein - dann aendern sich die Werte ja nicht.
Was ich dabei dann mache guck ich mal... Geht da auch eine Methode die mit show/ hide zusammen aufgerufen wird, um es auf Model-Werte zurueck zu setzen? Je nachdem was ich sonst bei show/ hide ueberschreibe...

**Comment by Dav1dK** [comment]
Ich fände es schlecht wenn man dem Kontrollfenster explizit sagen muss, die Werte zu übernehmen.
Am besten wäre es halt wenn das Kontrollfenster das Model observer würde und Änderungen selbständig mitbekommt. Ist das viel Arbeit?

**Comment by Dav1dK** [comment]
Das Reset ist übrigens nicht das einzige Problem: Szenarien verändern die Werte ebenfalls. Ich denke dann ist es unumgänglich, dass das Control Window das model observed.

**Comment by NikoWil** [comment]
Ja, es wird ein Observer

**Comment by NikoWil** [comment]
Frage: wie kann man auf die Temperatur passend reagieren?

Observen fuehrt zz dazu, dass die Temperatur nichtmehr geaendert werden kann. Aktueller Fall: man zieht den Slider, die Temperatur im Tank aendert sich leicht, Observer (ControlWindow) wird alarmiert, rundet den Wert im Tank auf den naechsten int und setzt sich damit wieder auf den alten Wert.

Faellt nicht auf, wenn nur sehr kleine Fluessigkeitsmengen im Tank sind, da dann Aenderungen zustande kommen koennen.

**Comment by ByteHamster** [comment]
Sowas hatte ich erwartet... Observer ignorieren, wenn man gerade geändert hat?

**Comment by NikoWil** [comment]
Also jedes mal eine TimeStamp anlegen und im Observer damit vergleichen...?

Wuerde gehen faende ich aber sehr unschoen.

**Comment by ByteHamster** [comment]
Mach dir eine Variable, die du immer aktualisierst, wenn gerade die valueChanged aufgerufen wurde. Dann im Observer nach dieser Variable filtern. Oder so ähnlich

**Comment by ByteHamster** [comment]
Moment nein. Das funktioniert nicht

**Comment by ByteHamster** [comment]
Wobei doch. Ist ja nicht Multi threaded... 

Also

JustSetValue=val
SetTemp(val) 
Changed Listener.onChanged

Observer 
If(justSetVauel == val) return

**Comment by NikoWil** [comment]
Aber es gilt ja nicht val == val

Angenommen aktuelle Temperatur 230.
ich will auf 0 setzten

Setze also 0
Im Tank wird gemixt, es entsteht 249.9
249.9 -> 250
250 != 0
Mein Slider wird auf 250 zurueckgesetzt

**Comment by NikoWil** [comment]
Oder man macht da die Temperaturen unabhaengig. Dass der Slider eben die Temperatur vom Zufluss als Abhaengigkeit hat, nicht die vom Tank wie bisher, was ja nicht so ganz passt...

**Comment by ByteHamster** [comment]
Wow das ist mir gar nicht aufgefallen. Der Slider darf sich Natürlich nicht einfach nur an der Temperatur vom Tank richten... Der ist ja für die input Temperatur

**Comment by NikoWil** [comment]
Wo bekomme ich die aus dem Model her?

**Comment by ByteHamster** [comment]
Gibt keinen Getter ^^

**Comment by NikoWil** [comment]
Klingt nach noch einem neuen Issue... Willst du oder soll ich?

**Comment by ByteHamster** [comment]
Ne bau es einfach selber ein

**Comment by ByteHamster** [comment]
Wie können nicht noch länger waren

**Comment by NikoWil** [comment]
Ich hab es jetzt mal an getInputTemperature(TankSelector selector) der ProductionSite geknuepft. Das hilft auch nicht.
