### ISSUE TITLE
[doc] Are OPC UA alarms synchronous or asynchronous? 

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#30]

**Comment by ByteHamster** [comment]
Asynchronous

**Comment by ByteHamster** [comment]
Haben Alarme ein Ende oder sind sie einmalige Ev nts

**Comment by Dav1dK** [comment]
Ich vermute sie sind einmalig, denn sie werden ja asynchron versendet. Ich kann mir nicht richtig vorstellen wie sie ein Ende haben könnten.

**Comment by ByteHamster** [comment]
Wie machen wir dann die Ampel? Die müsste ja dann wissen, wann der kritische Zustand zuende ist. Oder merkt sie das im Rahmen der normalen Aktualisierungen?

**Comment by HansMartinA** [comment]
Im Rahmen der normalen Aktualisierungen.
