### ISSUE TITLE
Drawer

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#300]
Wenn der Tank drüber leer ist, sollten sich die Durchflussmesser nicht drehen

**Comment by ByteHamster** [comment]
Verschieben der Regler lässt die RotatingDrawer springen

**Comment by NikoWil** [comment]
Dann muss bei den RotatingDrawern wohl doch die bisherige Drehung und die Zeitdifferenz mit beruecksichtigt werden. Sonst tut er beim Verschieben des Reglers so, als haette er sich schon immer mit neuer Geschwindigkeit gedreht und hat entsprechend eine andere Position.

Kann ich heute abend rein machen.

**Comment by NikoWil** [comment]
Problem: Wenn der Tank leer ist und inflow <= outflow mit inflow > 0 bleibt der Tank leer. Dennoch fliesst etwas.

Um den Fall abzufangen muesste jeder ValveDrawer mehr Teile der Simulation kennen als ich gut finde (eigene Pipe, Tank darueber, Pipe ueber dem Tank darueber)

**Comment by Dav1dK** [comment]
Idee: wir fügen der Pipe eine Methode hinzu die einfach angibt ob Flüssigkeit im ersten "Teil" der Pipe ist. Dann muss sich der Drawer drehen.
Den Fall, dass in der Pipe weniger Flüssigkeit als möglich ist, würde ich ignorieren, denn das kann nur in einem einzigen Aktualisierungsschritt passieren (wenn der Tank kurz vor leer ist).

**Comment by NikoWil** [comment]
Was genau muss ich da im Liquid alles pruefen?
Ich hab mir die Klasse gerade angesehen und bin leicht verwirrt wie genau sich "Fluessigkeit im ersten Teil" pruefen laesst.

**Comment by ByteHamster** [comment]
> Ich hab mir die Klasse gerade angesehen und bin leicht verwirrt wie genau sich "Fluessigkeit im ersten Teil" pruefen laesst.

Die Methode ist noch nicht drin

**Comment by NikoWil** [comment]
Ich weiss.
Es ging darum was geprueft werden muss, wenn man die Methode schreibt.
Nicht, dass die queue leer ist.
Dass das erste Element null ist?
Dass amount im ersten Element 0 ist?
Oder im Head?

**Comment by ByteHamster** [comment]
Hmm das geht momentan tatsächlich nicht, weil es als reine queue implementiert ist. Dann müsste man wahrscheinlich eine double ended queue draus machen

**Comment by Dav1dK** [comment]
Du musst prüfen ob der Amount des ersten Elements == 0 ist. Aber dazu musst du, wie ByteHamster sagte, die Queue zu einer double ended Queue machen.
