### ISSUE TITLE
Prüfen ob es Sinn macht eine Untergrenze für die Größe der Fenster festzulegen

### ISSUE THREAD

**Issue by Dav1dK** [ByteHamster/PSE#305]

**Comment by ByteHamster** [comment]
Ich bin dagegen, Untergrenzen zu definieren. Kann doch jeder skalieren wie er will... Außer man macht die Grenzen sehr klein.

**Comment by NikoWil** [comment]
Passen koennte eher ein gefordertes Seitenverhaeltnis.
Dass die Simulation z.B. nicht so flach werden darf, dass der Motor oben aus den Tanks rausguckt.

Aber die Groesse selbst laesst sich an fuer sich beliebig einstellen, nur die mangelnde Aufloesung des Bildschirms auf Nutzerseite kann dabei ein Problem sein, nicht dass Dinge falsch dargestellt werden.

**Comment by ByteHamster** [comment]
Ich hab glaub noch nie ein Programm benutzt, das ein bestimmtes Seitenverhältnis fordert...

**Comment by NikoWil** [comment]
Nicht fest ein Seitenverhaeltnis.
Nur illegale Verhaeltnisse nicht erlauben.
Im Sinne mach es so flach wie du willst, nur nicht so weit, dass unsinnige Sachen angezeigt werden.

Aber ob es doppelt oder viermal so hoch wie breit ist ist egal, so lange es im sinnvollen Bereich bleibt.

Waere mMn hier sinnvoll. Gerade wegen des MotorDrawers.

**Comment by NikoWil** [comment]
Das habe ich in der Form zwar auch noch nicht gesehen, aber wenn es passt passt es.

Besser als viele Spiele die ja direkt eine Liste an moeglichen Aufloesungen vorgeben und da noch weniger Freiheit erlauben.

**Comment by ByteHamster** [comment]
Fehlt noch auf client seite
