### ISSUE TITLE
[simulation-view] Interessantes Maximierungs-Verhalten.

### ISSUE THREAD

**Issue by HansMartinA** [ByteHamster/PSE#309]
Verschiedene Tests mit dem Nicht-Maximieren und anschließendem Maximieren brachten einen interessanten Effekt zustande beim maximierten Fenster:
![grafik](https://cloud.githubusercontent.com/assets/23618805/23572997/420522d0-0073-11e7-8233-8f8bda70ed1f.png)
Nähere empirische Untersuchungen haben ergeben:
Wird das Fenster bspw. auf folgende Größe **nicht-maximiert** gestellt:
![grafik](https://cloud.githubusercontent.com/assets/23618805/23573017/6c2569f8-0073-11e7-9538-51481268ad00.png)
und anschließend wieder maximiert, so sieht man am dargestellten Ausschnitt, dass die Tanks entsprechend der Fenstergröße richtig gezeichnet werden. Allerdings wird eine Größe nicht richtig gesetzt und verbleibt in der gleichen Größe wie im nicht-maximierten Größe und bildet den Ausschnitt. Der Ausschnitt ist also gleich groß dem Canvas im zuvor nicht-maximierten Fenster.
![grafik](https://cloud.githubusercontent.com/assets/23618805/23573065/ba2e7f72-0073-11e7-9044-109c2486d66e.png)
Dieses Verhalten wurde bisher nur unter Windows beobachtet. Es kommt häufiger vor, aber unter bestimmten Umständen auch wieder nicht.

Update: Aus unbekannten Gründen ist es möglich, durch reines Minimieren und wieder Anzeigen bzw. durch das Iconifizieren und deren Umkehrung, d. h. ohne das Fenster in einen nicht-maximierten Zustand zu bringen, die vollständige Anzeige der Simulation wiederherzustellen. Allerdings funktionieren alle Anzeigen, die außerhalb des sichtbaren Ausschnittes lagen, nicht und sind nicht animiert. Alle Anzeigen innerhalb des sichtbaren Ausschnittes sind weiterhin animiert. Es ist nahe liegend, dass ein Screenshot hierfür nichts Wesentliches zeigt. Nach einem Nicht-Maximieren und Maximieren (so lange, bis die Simulation auf einmal wieder vollständig angezeigt wird) funktioieren alle Animationen wieder.

Update 2: Wenn das Fenster nicht maximiert ist und in der Größe beliebig geändert wird, kann der Effekt auch auftreten.
![grafik](https://cloud.githubusercontent.com/assets/23618805/23573765/c919d0e0-0078-11e7-8dfb-c1d92db41084.png)
Update 2b: Wie es scheint, sobald der Effekt mind. einmal in einem nicht maximierten Fenster auftritt, sind die ausklappenden Menüs der Menübar nicht mehr sichtbar.

**Comment by NikoWil** [comment]
Interessant ist hierbei noch, dass die Größe der Drawer komplett von der Canvasgröße abhängt.
Dass die Drawer im kleinen Ausschnitt groß gezeichnet werden heißt also insbesondere, dass der Canvas mit maximiert wurde.
Dennoch ist nur ein kleiner Teil des Bildschirms als Canvas genutzt.
Der Canvas besitzt also scheinbar zwei Größen gleichzeitig.
Wie das zustande kommt ist für mich bisher nicht ersichtlich.

**Comment by ByteHamster** [comment]
Hatte den Fehler unter Arch Linux / KDE auch schon
