### ISSUE TITLE
Inflow regler sollte oben sein

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#316]

**Comment by NikoWil** [comment]
Ich wuerde die Reihenfolge so lassen.
Dann ist der Regler, der bei allen Tabs gleich ist (outflow) auch ueberall an der gleichen Stelle und ueberall flow vor Rest.

Und so herum ist die Implementierung mMn schoener, da dann in der Superklasse einfach erst alles hinzugefuegt werden kann und die Unterklassen dann ihre Sachen einfach drunter packen koennen.

**Comment by ByteHamster** [comment]
Ja, die Implementierung ist definitiv so schöner. Ich hatte das aber auch schonmal gedacht und gestern hat sich dann noch Nina beschwert, dass die Reihenfolge nicht so intuitiv ist. Wäre also schon gut, wenn wir das tauschen könnten. Die Ventile sind ja auf dem Bildschirm auch anders herum angezeigt

**Comment by Dav1dK** [comment]
Ich fände es anderst rum auch intuitiver.

**Comment by NikoWil** [comment]
Na gut. Dann werde ich es noch aendern.

**Comment by ByteHamster** [comment]
#319
