### ISSUE TITLE
Progress indicator, während Milo Dinge tut

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#331]

**Comment by Dav1dK** [comment]
Ich denke immer noch, dass das zu komplex wird. Wir haben nicht mehr viel Zeit und ich halte es nicht für so wichtig (allerdings habe ich auch max. 5 Sekunden Verzögerung, nämlich beim starten der Konsole)

**Comment by ByteHamster** [comment]
Mittlerweile ist es einigermaßen schnell. Wegen 2 Sekunden braucht man sich tatsächlich nicht die Arbeit machen
