### ISSUE TITLE
Performance der Simulation verbessern 

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#337]

**Comment by ByteHamster** [comment]
Wie oft wird der Animation timer aufgerufen? Wahrscheinlich viel häufiger als wir es brauchen

**Comment by NikoWil** [comment]
AnimationTimer versucht 60 FPS zu rendern.
Wenn er das nicht schafft macht er weniger.

Im AnimationTimer gibt es auch erstmal keine Moeglichkeit, die FPS zu reduzieren.

**Comment by ByteHamster** [comment]
Dann mal ausprobieren, ob uns auch ein normaler Timer bei ca 25 fps reicht. Gerade Canvas ist relativ Ressourcen-hungrig

**Comment by Dav1dK** [comment]
https://wiki.openjdk.java.net/display/OpenJFX/Performance+Tips+and+Tricks
