### ISSUE TITLE
Alarme werden auch beim wieder auflösen angezeigt

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#366]
Meldung kommt auch, wenn gerade auf grün umgeschaltet wird

**Comment by HansMartinA** [comment]
Wenn du in den Code schaust, kannst du feststellen, dass die Alarme nur ausgelöst werden, wenn sie tatsächlich ausgelöst wurden. Der doppelte Alarm bei realer Auslösung und der Alarm bei Auflösung kommen dadurch zustande, dass es Interferenzen zwischen den BooleanReceivedListenern und FloatReceivedListenern bei den Übergängen kommt.  Dies sieht man auch an den Verläufen (es gibt einen Knick): Die BooleanReceivedListener verzeichnen einen niedrigeren / höheren Wert und lösen den Alarm aus, während anschließend die FloatReceivedListener mit dem Aktualisierungsintervall einen höheren / niedrigeren Wert empfangen und dadurch den Alarm kurzzeitig deaktivieren. Dann wird mit den nächsten Aktualisierungsintervall der niedrige / hohe Werte empfangen und der Alarm nochmal ausgelöst.
Die Ursache liegt also in OPC UA oder im MonitoringController.

**Comment by ByteHamster** [comment]
Dann sollten sich die Alarm Icons nur an den booleans orientieren. So war das ja auch glaub mal irgendwann mit den Alarmen geplant. Müsste halt erst der Controller fertig werden, sonst lässt sich das kaum machen

**Comment by HansMartinA** [comment]
Damit bleibt der Fehler. Selbst unter Berücksichtigung der Booleans kommt es zu diesem Wechsel.

**Comment by ByteHamster** [comment]
Das heißt, die booleans flackern auch?

**Comment by HansMartinA** [comment]
Ja.

**Comment by ByteHamster** [comment]
Gerade getestet, die reinen booleans flackern nicht. Das muss mit dem neu subscriben zusammenhängen

**Comment by HansMartinA** [comment]
Taucht immer noch manchmal auf.

**Comment by ByteHamster** [comment]
Jup. Hab ihn gerade gesucht

**Comment by ByteHamster** [comment]
Hatte auch nichts geändert, das das beheben würde
