### ISSUE TITLE
Makros genauer spezifizieren

### ISSUE THREAD

**Issue by Dav1dK** [ByteHamster/PSE#37]
Ich denke wir sollten die Makros noch viel genauer spezifizieren. Wir sollten beschreiben wie man Makros aufnimmt  und abspielt usw.
Außerdem frage ich mich, was passiert wenn das Makro beim abspielen wieder von vorne beginnt. Wird dann der Zustand der Simulation wieder zurückgesetzt oder läuft alles so weiter? Dann sehe ich nämlich das Problem, dass bestimmt nach einigen Durchläufen ein Tank leerläuft obwohl man das garnicht beabsichtigt hatte.

**Comment by ByteHamster** [comment]
Vordefinierte Szenarien statt Makros. Szenarien in Dateien definiert. Eigene können von Power Usern hinzugefügt werden
