### ISSUE TITLE
Temperatur alarm wird im Monitoring nicht angezeigt

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#376]

**Comment by HansMartinA** [comment]
Überhitzung wird angezeigt.

**Comment by ByteHamster** [comment]
Stimmt, Unterkühlung aber nicht

**Comment by HansMartinA** [comment]
Zwei Möglichkeiten: Entweder die minimale Temperatur auf -10°C setzen oder die Schwelle für die Unterkühlung auf +5°C oder +10°C.

**Comment by ByteHamster** [comment]
Bin für Schwelle. Wo ist die momentan? 0?

**Comment by HansMartinA** [comment]
Ja.

**Comment by ByteHamster** [comment]
Die Schwellen sind an verschiedensten Stellen doppelt. Eigentlich sollte sich das Monitoring einfach nur an das Boolean halten, dann passen die Schwellen und das Flackern ist weg. Dafür müsste man die Observer der Lampen weg machen und sie stattdessen über die booleans setzbar machen
