### ISSUE TITLE
Known Bugs

### ISSUE THREAD

**Issue by Dav1dK** [ByteHamster/PSE#378]
- Das Menü des Monitors funktioniert manchmal nicht (man kann dann die Settings nicht mehr öffnen, passiert vor allem wenn man sich am Anfang nicht direkt verbinden kann). Vermutlich ein JavaFX Bug
- Das verbinden mit OPC UA Servern dauert lange

**Comment by ByteHamster** [comment]
Das Menü funktioniert deshalb nicht, weil die disconnect fehlermeldung im Hintergrund angezeigt wird

**Comment by ByteHamster** [comment]
Außerdem bitte einzelne issues, das ist übersichtlicher

**Comment by Dav1dK** [comment]
Nein, es wird zu dem Zeitpunkt kein Dialog mehr angezeigt. Man kann einfach nicht auf den Knopf drücken, weil das Menü sofort wieder zu geht. Ich hab es Martin am Donnerstag gezeigt, der wusste auch keine Lösung.
Zu dem anderen Kommentar: hier will ich Bugs dokumentieren, von denen wir wissen, die wir aber nicht beheben können (also z.B. Milo oder JavaFX Bugs)

**Comment by ByteHamster** [comment]
Aah okay

**Comment by Dav1dK** [comment]
Der Monitor gibt manchmal eine mehrzeilige Zahlenfolge auf der Standardausgabe aus, von der wir nicht wissen woher sie kommt

**Comment by Dav1dK** [comment]
Milo wirft beim Beenden selten eine Exception
