### ISSUE TITLE
Fill level

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#379]
Fill level Gauges werden nicht aktualisiert

**Comment by HansMartinA** [comment]
Nach einem Test liegt das nicht an der MonitoringView, sondern an OPC UA oder dem MonitoringController. Mit einer Ausgabe im fillLevelListener bekam ich zu Anfang eine Ausgabe und wie ich einmal einen Alarm ausgelöst habe. Ansonsten nicht.
