### ISSUE TITLE
Es werden sehr viele alarm dialoge erstellt

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#383]

**Comment by HansMartinA** [comment]
Kannst du das bitt näher erläutern?

**Comment by ByteHamster** [comment]
Wenn man ein Szenario laufen lässt, wird man mit der Zeit überschwemmt. Wahrscheinlich ist das so gewollt. Muss mal überlegen, ob mir etwas einfällt

**Comment by HansMartinA** [comment]
Nun gut, mit jedem ausgelösten Alarm wird ein neuer Dialog angezeigt.
