### ISSUE TITLE
Deaktivierte Alarme aktualisieren Status nicht

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#384]
-Alarm deaktivieren
-Alarm auslösen
-Alarm aktivieren

Light is grün statt rot

**Comment by ByteHamster** [comment]
Der ist noch nicht behoben

-Alarm deaktivieren
-Alarm auslösen
**-stabilen Zustand herstellen**
-Alarm aktivieren

**Comment by HansMartinA** [comment]
Was heißt stabiler Zustand? Ich habe bereits was dazu vorbereitet.

**Comment by ByteHamster** [comment]
Stabiler Zustand heißt in=out=0
