### ISSUE TITLE
Undercool szenario löst auch underflow aus - dann hat man 2 Meldungen

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#414]

**Comment by marimbMax** [comment]
Ist das nicht gut ? Dann passiert mehr und man inbes. den Unterlauf.

**Comment by ByteHamster** [comment]
Es gehen halt im Abstand von 3 Sekunden direkt 2 Meldungen auf. Das ist ein bisschen verwirrend, wenn es doch 2 Szenarien gibt. Eins für underflow und eins für undercool. Dann sollte nicht undercool beides tun
