### ISSUE TITLE
Progressions Intervall

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#415]
Wenn sich die Progressions ans Aktualisierungsintervall halten, dann haben sie weniger Stufen bei langsamen Intervallen

**Comment by HansMartinA** [comment]
Das Aktualisierungsintervall kommt nicht an die Stelle der Progressions bzw. generell nicht ins Dashboard der Überwachungskonsole. Ich finde es daher unnötig, das Aktualisierungsintervall oder gar die Einstellungen rein zu reichen, nur damit die Progressions von langsamen Intervallen profitieren.

**Comment by ByteHamster** [comment]
okay, war auch hauptsächlich bloß ne Idee
