### ISSUE TITLE
opcua single read

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#428]
Die single read funktion wird mittlerweile nicht mehr benutzt. Soll sie drin bleiben (die war sowieso eine Änderung zum Entwurf). Finde aber generell könnte sie schon sinnvoll sein

**Comment by NikoWil** [comment]
Wenn sie gar nicht benutzt wird wuerde ich sie raus nehmen.

**Comment by HansMartinA** [comment]
Ich würde es eher drin lassen. Es gibt zwar keinen Grund mehr, sie drin zu lassen, aber jetzt haben wir schon diese Funktionalität. Da brauchen wir sie wieder nicht zu entfernen.

**Comment by Dav1dK** [comment]
Ich würde sie eher rausnehmen, aber das ist mir nicht sonderlich wichtig. Von mir aus auch drin lassen..

**Comment by marimbMax** [comment]
Ich bin auch für drinlassen.
