### ISSUE TITLE
Deaktivierte Alarme

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#434]
Deaktivierte Alarme werden in der Überwachungskonsole in grau angezeigt, anstatt sie überhaupt nicht anzuzeigen.

Ich persönlich finde das ja recht schick, ist aber ein Verstoß gegen das Pflichtenheft

> **GT 230:**
> Die vorhandenen Alarme werden in der \gls{Uberwachungskonsole} ausgeschalten (FA450, FA780) und anschließend wird der Schwellenwert in der \gls{Fertigungssimulation} überschritten. Dies wird in der \gls{Uberwachungskonsole} **nicht angezeigt**.

**Comment by HansMartinA** [comment]
Jetzt nicht mehr.

**Comment by ByteHamster** [comment]
Was?
