### ISSUE TITLE
Programm Icon und Name

### ISSUE THREAD

**Issue by ByteHamster** [ByteHamster/PSE#46]

**Comment by Dav1dK** [comment]
Womöglich etwas mit vernetzten Maschinen und Industrie 4.0?

**Comment by ByteHamster** [comment]
Simulatr
OSIP: **O**PC-UA **S**imulator for **I**ndustrial **P**lants
SIPS: **S**mall **I**ndustrial **P**lant **S**imulator
SIPSO: **S**mall **I**ndustrial **P**lant **S**imulator using **O**PC-UA
SOMLI: **S**imulating **O**PC-UA **M**achine **L**ink for the **I**ndustry 4.0
SIMLO: **S**imulating **I**ndustry 4.0 **M**achine **L**inks with **O**PC-UA

![img_20161207_170459](https://cloud.githubusercontent.com/assets/5811634/20975557/25c59c88-bca0-11e6-8da9-57ae43e8fd85.jpg)

**Comment by ByteHamster** [comment]
Können es ja als working title "Project Gemini" nennen oder so :P

**Comment by ByteHamster** [comment]
Deadline ist 9.12. um 11:15 Uhr
Bitte Kommentare zu Name und Icon
Jeder bitte 1-2 Lieblings-Namen oder Icons auswählen.
Bei kreativen Ideen gerne schreiben, ansonsten wird es eins von denen hier.

Icons (für einfache Benennung):
```
 1  2  3
 4  5  6
 7  8  9
10 11 12
```

**Comment by NikoWil** [comment]
Name: Ich bin fuer OSIP oder SIMLO.
Icon: Ich bin fuer 5, evtl noch ein Symbol in der rechten Haelfte fuer den Empfaenger?

**Comment by marimbMax** [comment]
OSIP und Icon 6.

**Comment by Dav1dK** [comment]
Ich bin auch für OSIP und für eine Mischung aus 8 und 11 (also z.B. das Zahnrad in die obere rechte Ecke von 8).

**Comment by ByteHamster** [comment]
We have a winner!
**OSIP: OPC-UA Simulator for Industrial Plants**

Ich stimme für **Icon 6**, also wird es das. Entwürfe folgen.
