### ISSUE TITLE
Überarbeitung

### ISSUE THREAD

**Issue by Dav1dK** [ByteHamster/PSE#52]
- [x]  Kann-Anforderungen z.b. farblich abheben statt in einenem Kapitel
- [x]  Zurücksetzen von der "Überlauf" Meldung aus
- [x] Alarmschwelle "inplace" ändern

**Comment by HansMartinA** [comment]
- [x] Titelseite

**Comment by ByteHamster** [comment]
Was würdest du auf die Titelseite machen? Bin dafür, einfach nur das Icon des Programms da anzuzeigen.

**Comment by ByteHamster** [comment]
- [x] Bild (Systemskizze) nochmal in Einleitung einbinden

**Comment by Dav1dK** [comment]
Aber ich würde auch die kurze Projektbeschreibung und unsere Namen auf die Titelseite schreiben.

**Comment by Dav1dK** [comment]
- [x] Menüführung nicht so genau beschreiben

**Comment by ByteHamster** [comment]
Namen sind doch schon auf der Titelseite

**Comment by HansMartinA** [comment]
Mit Titelseite meine ich eine Seite, auf der unsere Namen, das Name des Projektes und das Projekticon steht. Fertig. Ich denke, mehr braucht es nicht.

**Comment by ByteHamster** [comment]
Also kann man die Titelseite abhaken?

**Comment by Dav1dK** [comment]
Ja, ich habs abgehackt.
