### ISSUE TITLE
MVC

### ISSUE THREAD

**Issue by NikoWil** [ByteHamster/PSE#80]
Ein Kriterium von PSE ist ja, dass wir das ganze als MVC Architektur umsetzen.
Wie soll das hier eigentlich geschehen?
Ich koennte mir zz hoechstens zwei MVCs vorstellen. Einmal mit Fertigungssimulation, einmal mit Ueberwachungskonsole. Die sind ja auch getrennte Programme.

**Comment by Dav1dK** [comment]
Ja mehr MVC können wir, denk ich, nicht unterbringen. So macht das schon Sinn.

**Comment by ByteHamster** [comment]
Natürlich, mehr als 2 MVC wäre sinnlos.

Model: Die Klasse "Tank"
View: Die Anzeige der Simulation, greift auf das Model zu
Controller: Setzt bei geänderten Einstellungen die Werte im Model, aktualisiert den Server und weist das UI an, die neuen Werte anzuzeigen

**Comment by ByteHamster** [comment]
@HansMartinA Das wolltest du machen, oder?

**Comment by HansMartinA** [comment]
Ja.
