### ISSUE TITLE
Einleitungsbild

### ISSUE THREAD

**Issue by NikoWil** [ByteHamster/PSE#81]
Wollen wir das Bild, das aktuell in der Einleitung ist, so lassen?

Ich finde es entspricht nicht ganz dem was wir da wollen. Fuer mich war es eher Skizze, um uns am Anfang klar zu machen was wir wollen aber ich wuerde es sauberer nochmal neu machen, ohne die ganzen Pfeile. Die Infos koennen dann ja in die Beschreibung der Grafik.

**Comment by Dav1dK** [comment]
Da stimmte ich zu.

**Comment by ByteHamster** [comment]
Die umlet datei ist im git ;) Einfach bearbeiten

**Comment by NikoWil** [comment]
Mach ich, wenn ich mich inspiriert fuehle. So wie der Text gestern ;)
