### ISSUE TITLE
3D Darstellung

### ISSUE THREAD

**Issue by NikoWil** [ByteHamster/PSE#83]
Ist die 3D Darstellung im Pflichtenheft Anhang wirklich noetig?
Sie sagt uns ja nichts ueber das, was wir machen werden. Nur, was vorher einmal ueberlegt und verworfen wurde.

**Comment by ByteHamster** [comment]
Ich wollte das irgendwo drin haben. War so viel Arbeit :D Wenn du meinst das könnte sonst Abzug geben, dann würde ich schweren Herzens zustimmen, es rauszumachen
