### ISSUE TITLE
Keine Server

### ISSUE THREAD

**Issue by HansMartinA** [ByteHamster/PSE#96]
Was passiert, wenn keine Server mehr für den OPC UA Client zu erreichen sind? Wie reagiert die Überwachungskonsole darauf?

**Comment by ByteHamster** [comment]
Generell nicht "Keine Server". Schon sobald einer der Server nicht mehr erreichbar ist, würde ich eine Fehlermeldung zeigen. Dialogbox oder so.

**Comment by Dav1dK** [comment]
Ich würde sagen, dann öffnet sich das normale Fenster mit den Verbindungseinstellungen,mit dem Unterschied, dass oben eine kleine Fehlermeldung steht.

**Comment by HansMartinA** [comment]
Ich habe es nun so gemacht, dass ein Dialog mit Fehler und die Einstellungen kommen. So kann der Nutzer u. U. neue Verbindungsinformationen eintragen und erfährt, was mit der Verbindung geschehen ist.

**Comment by ByteHamster** [comment]
Kann man den issue dann schließen?
